apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8sdemo-mariadb-pvclaim
  labels:
    app: k8sdemo-mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi