server:
  port: 8002
spring:
  application:
    name: seata-learn-points
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.11:3306/seata_points
    password: root
    username: root
  # nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.11:8848
        username: nacos
        password: nacos
  profiles:
    active: seata
ribbon:
  ###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ReadTimeout: 500000
  ###指的是建立连接后从服务器读取到可用资源所用的时间。
  ConnectTimeout: 50000
