apiVersion: v1
kind: Pod
metadata:
  name: lifecle-pod1
  labels:
    app: lifecle-pod1
spec:
  containers:
    - name: lifecle-pod1
      image: busybox:1.32.0
      imagePullPolicy: IfNotPresent
      lifecycle:
        postStart:
          exec:
            command: ['mkdir','-p','/data/k8s/index.html']
      command: ['sh','-c','sleep 5000']
  restartPolicy: Always
