apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat9
  labels:
    app: tomcat9
spec:
  replicas: 1
  template:
    metadata:
      name: tomcat9
      labels:
        app: tomcat9
    spec:
      containers:
        - name: tomcat9
          image: tomcat:9.0.20-jre8-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      app: tomcat9
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat9-svc
spec:
  selector:
    app: tomcat9
  ports:
    - port: 8888
      targetPort: 8080
      protocol: TCP
      nodePort: 31710
  type: NodePort